docs: correct location of `initialColorModeName: 'light'`
system-ui/theme-ui pull request #1922
Opened 2021-09-07 03:27 UTC by gleich

It seems as though `initialColorModeName: 'light'` should no longer be stored in the root theme object but in the colors object instead. Here I moved it in the documentation to reflect that change.

2021-09-07 10:31 UTC, hasparus commented
Does this work for you? 👀

I mean... it should work if you put in the `theme.config` object.

https://theme-ui.com/theming#configuration-flags

If it's inside of `colors` then it's just color.

2021-09-07 10:32 UTC, hasparus commented
If putting it inside `.config` doesn't work in your app, could you post a bug report with some more details?

2021-09-07 10:33 UTC, hasparus requested changes
If putting it inside `.config` doesn't work in your app, could you post a bug report with some more details?

2021-09-07 14:04 UTC, gleich commented
Ah, I'm sorry. I misread the warning I was getting from eslint. Fixed!

2021-09-07 15:19 UTC, hasparus approved these changes
Thanks for your contribution!

2021-09-08 05:55 UTC, lachlanjc approved these changes
Thanks Matt!!

2021-09-08 05:55 UTC, merged

2021-09-08 07:03 UTC, hasparus commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.11.2-develop.3`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.2-develop.3) :rocket:

2021-09-08 10:24 UTC, hasparus commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.11.2`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.2) :rocket: